app/models/auth_model.py
from __future__ import annotations  
from typing import TYPE_CHECKING

from sqlalchemy import Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship
from werkzeug.security import check_password_hash
from werkzeug.security import generate_password_hash

from app import db

if TYPE_CHECKING:
    from .history_model import History


class User(db.Model):  
    # __tablename__ = "user_account"  
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(30), unique=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    
    histories : Mapped[list[History]] = relationship('History', back_populates='owner')  

    @property
    def password(self):
        raise AttributeError('passowrd is not readabilty attribute')
    
    @password.setter
    def password(self, value: str) -> None:
        """Store the password as a hash for security."""
        self.password_hash = generate_password_hash(value)

    def check_password(self, value: str) -> bool:
        '''比對註冊密碼和輸入密碼'''
        return check_password_hash(self.password_hash, value)

app/models/history_model.py
# from __future__ import annotations
from typing import TYPE_CHECKING

from datetime import datetime
from datetime import timezone
from sqlalchemy import Integer, String, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app import db
from app.models.auth_model import User

# if TYPE_CHECKING:
#     from .auth_model import User


def now_utc() -> datetime:
    return datetime.now(timezone.utc)


class History(db.Model):
    # __tablename__ = ""
    id: Mapped[int] = mapped_column(primary_key=True)
    owner_id: Mapped[int] = mapped_column(Integer, ForeignKey('user.id'))
    original_text: Mapped[str] = mapped_column(String(255))
    translated_text: Mapped[str] = mapped_column(String(255))
    created_at: Mapped[datetime] = mapped_column(DateTime, default=now_utc)

    owner: Mapped[User] = relationship(lazy="joined", back_populates='histories')

app/__init__.py
from flask import Flask
from flask.cli import with_appcontext  
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase

import os
import click  
from dotenv import load_dotenv


class Base(DeclarativeBase):
    pass    
db = SQLAlchemy(model_class=Base)  


def create_app(test_config=None):
    """建立並配置一個 Flask 應用程式的實體"""
    app = Flask(__name__)
    
    load_dotenv()  
    db_url = os.environ.get("SQLALCHEMY_DATABASE_URI")  
    if db_url is None: 
        db_url = "sqlite:///flaskr.sqlite"


    app.config.from_mapping(
        SECRET_KEY=os.environ.get("SECRET_KEY", "dev"),  
        SQLALCHEMY_DATABASE_URI=db_url,
    )  
    if test_config is None:
        app.config.from_pyfile("config.py", silent=True)
    else:
        app.config.update(test_config)


    db.init_app(app)  
    app.cli.add_command(init_db_command)  

    from .views import home_bp
    from .views import auth_bp

    app.register_blueprint(home_bp)
    app.register_blueprint(auth_bp)
    app.add_url_rule("/", endpoint="index")

    return app


def init_db():
    db.drop_all()
    db.create_all()

@click.command("init-db")  
@with_appcontext  
def init_db_command():
    """Clear existing data and create new tables."""
    init_db()
    click.echo("Initialized the database.")

app/views/__init__.py
from .home import bp as home_bp
from .auth import bp as auth_bp

app/views/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for 
)

from app import db
from app.models.auth_model import User  

bp = Blueprint('auth', __name__, url_prefix="/auth")


def login_required(view):
    '''
    用於確認使用者是否已登入的裝飾器，之後會添加到需要此功能的功能(路由)中。
    若使用者已登入，則會繼續執行功能；若沒有則重新導向登入頁面。
    '''
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view


@bp.before_app_request
def load_logged_in_user():
    '''
    此裝飾器用於註冊一個函式在應用程序請求之前執行，
    在這裡我們將在請求前先從 session 中載入使用者的資訊
    '''
    user_id = session.get("user_id")  

    if user_id is not None:
        g.user = db.session.get(User, user_id)
    else:
        g.user = None


@bp.route("/register", methods=("GET", "POST"))
def register():
    """註冊新使用者。
    驗證使用者使用者名稱未被使用。為了安全，雜湊化密碼。
    """
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        error = None  

        if not username:
            error = "Username is required."
        elif not password:
            error = "Password is required."
        elif db.session.execute(
            db.select(db.select(User).filter_by(username=username).exists())
        ).scalar():
            error = f"User {username} is already registered."

        if error is None:
            db.session.add(User(username=username, password=password))
            db.session.commit()
            return redirect(url_for("auth.login"))

        flash(error)  

    return render_template("auth/register.html")  


@bp.route("/login", methods=("GET", "POST"))
def login():
    """登入已註冊的使用者，並將其添加至 session 中。"""
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        error = None
        select = db.select(User).filter_by(username=username)
        user = db.session.execute(select).scalar()

        if user is None:  
            error = "Incorrect username."
        elif not user.check_password(password):  
            error = "Incorrect password."

        if error is None:  
            session.clear()
            session["user_id"] = user.id
            return redirect(url_for("index"))

        flash(error)

    return render_template("auth/login.html")


@bp.route("/logout")
def logout():
    """清除當前 session(例如：使用者 ID)."""
    session.clear()
    return redirect(url_for("index"))

app/views/home.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request,session ,url_for
)

from app.utils.translation import translate_func

from app import db
from app.models.history_model import History
# from app.views.auth import login_required

bp = Blueprint('home', __name__)


@bp.route('/')
def index():

    translated_text = request.args.get('translated_text')
    if session.get("user_id"):
        select = db.select(History) \
            .where(History.owner_id == session["user_id"]) \
            .order_by(History.created_at.desc())
        historys = db.session.execute(select).scalars()
    else:
        historys = None
    
    datas = {
        'translated_text': translated_text,
        'historys': historys
    }

    return render_template('home/index.html', **datas)


@bp.route('/translate', methods=['POST'])
def translate():
    original_text = request.form['original_text']
    error = None

    if not original_text:
        error = 'Please enter text first'
    if error != None:
        flash(error)
    else:   
        translated_text = translate_func(original_text)
        if g.user != None:
            db.session.add(History(
                original_text=original_text, 
                translated_text=translated_text, 
                owner=g.user  
            ))
            db.session.commit()

        return redirect(url_for('home.index', translated_text=translated_text))

    return render_template('home/index.html')

app/templates/base.html
<!doctype html>
<title>{% block title %}Home{% endblock %} - Translator</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1><a href="{{ url_for('index') }}">Translator</a></h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <!-- 如果路由還沒開發好，可先填入 '#' 避免出現錯誤  -->
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

app/templates/home/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

app/templates/home/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="translation-form">
    <form action="{{ url_for('home.translate') }}" method="post">
      <label for="original_text">Original text：</label>
      <input type="text" name="original_text" id="original_text">
      <input type="submit" value="Translate">
    </form>
    <p class="translation">Translation：{% if translated_text %}{{ translated_text }}{% endif %}</p>
  </div>

  <hr>

  <div class="history">
    <header>
      <h2>History</h2>
    </header>
    {% if historys  %}
      {% for history in historys %}
        <div class="history_item">
          <p class="text">{{ history.original_text }}</p>
          <p class="arrow">↓</p>
          <p class="text">{{ history.translated_text }}</p>
          <p class="time">{{ history.created_at }}</p>
        </div>
        <hr>
      {% endfor %}
    {% else %}
      <div class="history_item">
        <p class="text">PLEASE LOG IN FIRST</p>
      </div>
    {% endif %}
   </div>
{% endblock %}

app/templates/home/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ post.delete_url }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}

app/templates/test.html
<!DOCTYPE html>
<html>
  <head>
    <title>My App</title>
  </head>
  <body>
    <h1>My App</h1>
    <form action="{{ url_for('home.translate') }}" method="post">
      <label for="original_text">原文：</label>
      <input type="text" name="original_text" id="original_text">
      <button type="submit">翻譯</button>
    </form>
    <p>譯文：{% if translated_text %}{{ translated_text }}{% endif %}</p>
  </body>
</html>